# Generated by Django 2.1.1 on 2018-09-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=10)),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
                ('item_low', models.DecimalField(decimal_places=10, max_digits=20)),
                ('item_high', models.DecimalField(decimal_places=10, max_digits=20)),
                ('item_open', models.DecimalField(decimal_places=10, max_digits=20)),
                ('item_close', models.DecimalField(decimal_places=10, max_digits=20)),
                ('item_volume', models.DecimalField(decimal_places=10, max_digits=20)),
                ('time_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('trade_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('size', models.DecimalField(decimal_places=10, max_digits=20)),
                ('side', models.CharField(choices=[('BUY', 'buy'), ('SELL', 'sell')], max_length=4)),
            ],
        ),
    ]
