# Generated by Django 2.1.1 on 2018-09-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_auto_20180917_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='candle',
            unique_together={('item_id', 'base_currency', 'quote_currency')},
        ),
    ]
