# Generated by Django 2.1.1 on 2018-09-19 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_auto_20180918_2218'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candle',
            unique_together={('item_id', 'base_currency', 'quote_currency', 'time_created')},
        ),
    ]
